import contextlib
import io
import json
import os
from pathlib import Path
import sqlite3
import sys
import tempfile
import unittest
from unittest.mock import patch

import distill_sessions as D
import ingest_codex_sessions as C
import ingest_hermes_sessions as H
import ingest_sessions as I
import schema_v3 as S


class ContinuationTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory(prefix="kal-continuation-")
        self.addCleanup(self.temp.cleanup)
        self.root = Path(self.temp.name)
        self.out = self.root / "distilled"
        self.done = self.out / ".done"
        self.done.mkdir(parents=True)
        self.bundle = self.root / "bundle"
        self.bundle.mkdir()
        for target in (patch.dict(os.environ, {"HOME": str(self.root), "KAL_VAULT": str(self.bundle)}, clear=True),
                       patch.object(D, "OUT", str(self.out)), patch.object(D, "DONE", str(self.done)),
                       patch.object(D, "REVIEW", str(self.out / "review.tsv")),
                       patch.object(I, "EXCLUDE", str(self.root / "exclude.txt")),
                       patch.object(D.ledger, "append")):
            target.start()
            self.addCleanup(target.stop)
        self.since = I.epoch("2020-01-01T00:00:00Z")
        self.secret = "ghp_" + "A" * 36

    def record(self, agent="claude", sid="session", **extra):
        return {"agent": agent, "session_id": sid, "project": "fixture", "text": "Collected transcript",
                "first_ts": "2020-01-01T00:00:00Z", "last_ts": "2020-01-02T00:00:00Z", "n_msg": 2, **extra}

    def page(self, path, *, agent="claude", sid="session", blocked=False, continues=None, published=False):
        provenance = f"sources:\n  - resource: {agent}-session://{sid}" if published else f"session_id: {sid}\nsession_agent: {agent}"
        text = f"---\ntitle: Human changed title\n{provenance}\n"
        if blocked:
            text += '"no_llm": true # reviewed\n'
        if continues:
            text += f"continues: {continues}\n"
        path.write_text(text + "---\nSaved conclusion.\n")

    def run_main(self, rec, answer="SKIP", restart=False):
        with patch.object(D, "corpus_records", return_value=([rec], [])), \
                patch.object(sys, "argv", ["distill_sessions.py", "--workers", "1"] + (["--restart"] if restart else [])), \
                patch.object(D, "call", return_value=answer) as model, contextlib.redirect_stdout(io.StringIO()):
            result = 0
            try:
                D._main_distill()
            except SystemExit as error:
                result = error.code
        return result, model

    def test_local_and_published_identity_carries_privacy_without_rewriting_public_pages(self):
        published = self.bundle / "renamed-public.md"
        self.page(published, blocked=True, published=True)
        self.page(self.out / "renamed-local.md")
        self.page(self.out / "old-continuation.md", continues="missing-original")
        public_before = published.read_bytes()
        snapshot = D.privacy_snapshot()
        self.assertTrue(D.no_llm_of_pages([], self.record(), snapshot))
        D.carry_privacy(snapshot)
        self.assertTrue(all(S.doc_meta(path.read_text())[2] for path in self.out.glob("*.md")))
        self.assertEqual(published.read_bytes(), public_before)
        docs = [{"title": "Human supplied continuation", "doc_type": "decision", "why_captured": "reviewed",
                 "tags": [], "body": "Already reviewed, not generated by a model."}]
        made = D.write(self.record(), docs, {}, continues="missing-original")
        self.assertTrue(S.doc_meta((self.out / (made[0][0] + ".md")).read_text())[2])
        published.unlink()
        self.assertTrue(D.no_llm_of_pages([], self.record()))

    def test_restart_and_missing_marker_are_gated_before_any_model_call(self):
        self.page(self.bundle / "human-renamed.md", blocked=True, published=True)
        for restart in (False, True):
            with self.subTest(restart=restart):
                result, model = self.run_main(self.record(), restart=restart)
                self.assertEqual(result, 0)
                model.assert_not_called()
                self.assertFalse(list(self.done.iterdir()))

    def test_session_agent_namespace_and_body_provenance_do_not_cross_gate(self):
        self.page(self.bundle / "private.md", agent="codex", blocked=True, published=True)
        (self.bundle / "prose.md").write_text("---\nno_llm: true\n---\nsources:\n  - resource: claude-session://session\n")
        self.assertFalse(D.no_llm_of_pages([], self.record()))
        self.assertTrue(D.no_llm_of_pages([], self.record("codex")))

    def test_existing_local_flag_stays_true_and_protects_renamed_pages(self):
        original = self.out / "renamed.md"
        self.page(original, blocked=True)
        before = original.read_bytes()
        self.assertEqual(self.run_main(self.record())[0], 0)
        self.assertEqual(original.read_bytes(), before)

    def codex_fixture(self):
        path = self.root / "rollout-fixture.jsonl"
        rows = [{"type": "session_meta", "payload": {"id": "session", "cwd": "/fixture"}}]

        def add(stamp, kind, payload):
            rows.append({"timestamp": stamp, "type": kind, "payload": payload})

        def message(stamp, body, role="user"):
            add(stamp, "response_item", {"type": "message", "role": role,
                                        "content": [{"type": "input_text" if role == "user" else "output_text", "text": body}]})

        message("2020-01-01T00:00:00Z", "BOUNDARY_CANARY already reviewed")
        message("2019-12-31T19:00:00-05:00", "OFFSET_BOUNDARY_CANARY")
        message(None, "UNKNOWN_TIMESTAMP_CANARY")
        message("2020-01-01T12:00:00Z", "<INSTRUCTIONS>INJECTED_CANARY</INSTRUCTIONS>\nReal follow-up " + self.secret)
        message("2020-01-02T00:00:00Z", "Final decision", "assistant")
        add("2020-01-02T00:00:00Z", "event_msg", {"type": "agent_message", "message": "Final decision"})
        add("2020-01-01T23:00:00Z", "event_msg", {"type": "user_message", "message": "Event-only user follow-up"})
        message("2020-01-01T20:00:00Z", "DEVELOPER_CANARY", "developer")
        add("2020-01-01T20:00:00Z", "response_item", {"type": "function_call_output", "output": "TOOL_CANARY"})
        message("2020-01-02T00:00:01Z", "UNCOLLECTED_CANARY")
        path.write_text("\n".join(json.dumps(row) for row in rows) + "\n")
        return self.record("codex", abs_path=str(path))

    def test_codex_tail_reuses_channels_dedupe_injection_mask_and_boundaries(self):
        rec = self.codex_fixture()
        tail = D.continuation_tail(rec, self.since)
        self.assertEqual(tail["n_msg"], 3)
        self.assertIn("Real follow-up", tail["text"])
        self.assertIn("Event-only user follow-up", tail["text"])
        self.assertEqual(tail["text"].count("Final decision"), 1)
        self.assertNotIn("CANARY", tail["text"])
        self.assertNotIn(self.secret, tail["text"])
        self.assertFalse(I.find_leaks(tail["text"]))
        collected = C.parse_rollout(rec["abs_path"])
        self.assertIn("BOUNDARY_CANARY", collected["text"])
        self.assertIn("UNCOLLECTED_CANARY", collected["text"])

    def hermes_fixture(self):
        path = self.root / "state.db"
        con = sqlite3.connect(path)
        self.addCleanup(con.close)
        numeric = {"started_at", "ended_at", "timestamp", "hidden", "active", "compacted", "_compressed_summary", "observed"}
        for table, columns in H.REQUIRED.items():
            con.execute(f"CREATE TABLE {table} (" + ", ".join(name + (" REAL" if name in numeric else " TEXT") for name in columns) + ")")

        def insert(table, **values):
            con.execute(f"INSERT INTO {table} ({','.join(values)}) VALUES ({','.join('?' for _ in values)})", list(values.values()))

        insert("sessions", id="session", source="cli", started_at=self.since - 10, hidden=0, end_reason="compression")
        insert("sessions", id="compressed", source="cli", started_at=self.since + 10, hidden=0, parent_session_id="session")
        insert("sessions", id="other", source="cli", started_at=self.since, hidden=0)
        insert("sessions", id="private-platform", source="telegram", started_at=self.since, hidden=0)

        def turn(body, stamp, sid="compressed", **fields):
            insert("messages", session_id=sid, role=fields.pop("role", "user"), content=body, timestamp=stamp, **fields)

        turn("BOUNDARY_CANARY", self.since, "session")
        turn("UNKNOWN_TIMESTAMP_CANARY", None)
        turn("Hermes follow-up " + self.secret, self.since + 20)
        turn(H.PRIOR_HEADER + "\nLive carrier request\n" + H.MERGED_DELIMITER + "\nSUMMARY_CANARY", self.since + 30, _compressed_summary=1)
        turn("Archived original turn", self.since + 40, active=0, compacted=1)
        turn("REWOUND_CANARY", self.since + 50, active=0, compacted=0)
        turn("OBSERVED_CANARY", self.since + 50, observed=1)
        turn("[System: SYNTHETIC_CANARY", self.since + 50)
        turn("TOOL_CANARY", self.since + 50, role="tool")
        turn(H.PEER_DM + "PEER_CANARY", self.since + 50)
        turn("OTHER_SESSION_CANARY", self.since + 50, "other")
        turn("PLATFORM_CANARY", self.since + 50, "private-platform")
        turn("Final Hermes decision", self.since + 86400, role="assistant")
        turn("UNCOLLECTED_CANARY", self.since + 86401)
        con.commit()
        return self.record("hermes", abs_path=f"{path}#session", members=["session", "compressed"])

    def test_hermes_tail_stitches_members_and_reuses_privacy_filters(self):
        rec = self.hermes_fixture()
        tail = D.continuation_tail(rec, self.since)
        self.assertEqual(tail["n_msg"], 4)
        for value in ("Hermes follow-up", "Live carrier request", "Archived original turn", "Final Hermes decision"):
            self.assertIn(value, tail["text"])
        self.assertNotIn("CANARY", tail["text"])
        self.assertNotIn(self.secret, tail["text"])
        self.assertEqual(I.epoch(tail["last_ts"]), self.since + 86400)

    def test_exclusion_cutoff_remains_strict_for_codex_and_hermes(self):
        for fixture in (self.codex_fixture, self.hermes_fixture):
            rec = fixture()
            with patch.object(I, "load_excluded", return_value={"session": self.since + 86400}):
                tail = D.continuation_tail(rec, self.since)
            self.assertNotIn("Final", tail["text"])
            with patch.object(I, "load_excluded", return_value={"session": None}):
                with self.assertRaisesRegex(ValueError, "excluded"):
                    D.continuation_tail(rec, self.since)

    def test_hermes_optin_requires_receipt_before_store_read(self):
        rec = self.record("hermes", abs_path=str(self.root / "never-open.db") + "#session")
        with patch.dict(os.environ, {"KAL_HERMES_SOURCES": "acp"}), \
                patch.object(H.claude_cli, "no_tools_verified", return_value=False), patch.object(H, "read_store") as read:
            with self.assertRaises(D.ThirdPartyGateError):
                D.continuation_tail(rec, self.since)
            read.assert_not_called()

    def test_codex_and_hermes_skip_advance_markers_and_zero_calls_on_rerun(self):
        for fixture in (self.codex_fixture, self.hermes_fixture):
            rec = fixture()
            marker = self.done / (rec["agent"] + "-session")
            marker.write_text(json.dumps({"last_ts": "2020-01-01T00:00:00Z", "pages": ["original-page"]}))
            result, model = self.run_main(rec)
            self.assertEqual(result, 0)
            model.assert_called_once()
            self.assertNotIn("CANARY", model.call_args.args[0])
            self.assertEqual(json.loads(marker.read_text()), {"last_ts": rec["last_ts"], "pages": ["original-page"]})
            result, model = self.run_main(rec)
            self.assertEqual(result, 0)
            model.assert_not_called()

    def test_codex_and_hermes_success_append_pages_with_original_provenance(self):
        reply = "<<<DOC>>>\ntitle: New conclusion\ndoc_type: decision\nwhy_captured: Review\ntags: fixture\n---\nA new reviewed decision.\n<<<END>>>"
        for fixture in (self.codex_fixture, self.hermes_fixture):
            rec = fixture()
            marker = self.done / (rec["agent"] + "-session")
            marker.write_text(json.dumps({"last_ts": "2020-01-01T00:00:00Z", "pages": ["original-page"]}))
            result, model = self.run_main(rec, reply)
            self.assertEqual(result, 0)
            model.assert_called_once()
            info = json.loads(marker.read_text())
            self.assertEqual(info["pages"][0], "original-page")
            self.assertEqual(len(info["pages"]), 2)
            page = (self.out / (info["pages"][-1] + ".md")).read_text()
            self.assertIn("session_agent: " + rec["agent"], page)
            self.assertIn("session_id: session", page)
            self.assertIn("continues: original-page", page)
            self.assertIn("New conclusion (continued)", page)

    def test_leak_verification_failure_never_advances_or_calls_model(self):
        for fixture in (self.codex_fixture, self.hermes_fixture):
            rec = fixture()
            marker = self.done / (rec["agent"] + "-session")
            marker.write_text(json.dumps({"last_ts": "2020-01-01T00:00:00Z", "pages": ["original"]}))
            before = marker.read_bytes()
            with patch.object(I, "find_leaks", return_value={"fixture-secret": 1}):
                result, model = self.run_main(rec)
            self.assertIn("1 continuation(s) failed", str(result))
            model.assert_not_called()
            self.assertEqual(marker.read_bytes(), before)

    def test_private_page_in_hidden_folder_and_malformed_frontmatter_fail_closed(self):
        hidden = self.bundle / ".private"
        hidden.mkdir()
        page = hidden / "renamed.md"
        self.page(page, published=True, blocked=True)
        self.assertTrue(D.no_llm_of_pages([], self.record()))
        page.write_text("---\nno_llm: true\nsources:\n  - resource: claude-session://session\n")
        result, model = self.run_main(self.record())
        self.assertIn("malformed", result)
        self.assertIn("cannot resolve privacy", result)
        model.assert_not_called()

    def test_unsafe_privacy_yaml_is_refused_before_construction_or_model_calls(self):
        import yaml
        import source_links as L

        doubling = "base: &b0 {value: canary}\n" + "\n".join(
            f"b{i}: &b{i} {{<<: [*b{i - 1}, *b{i - 1}]}}" for i in range(1, 6))
        cases = (
            doubling,
            "base: &base {x: y}\ncopy: *base",
            "copy: {<<: {x: y}}",
            "copy: {!!merge '<<': {x: y}}",
            "loop: &loop [*loop]",
            "nested: " + "[" * (L.MAX_YAML_DEPTH + 1) + "x" + "]" * (L.MAX_YAML_DEPTH + 1),
            "wide: [" + ",".join(["x"] * 17) + "]",
            'padding: "' + "x" * L.MAX_FRONTMATTER_CHARS + '"',
            "sources: [unterminated",
        )
        for root in (self.out, self.bundle):
            page = root / "untrusted.md"
            for fm in cases:
                with self.subTest(root=root.name, case=fm[:40]), \
                        patch.object(L, "MAX_YAML_NODES", 16 if fm.startswith("wide:") else L.MAX_YAML_NODES), \
                        patch.object(yaml.SafeLoader, "construct_document",
                                     side_effect=AssertionError("unsafe YAML reached construction")) as construct:
                    page.write_text('---\n"no_llm": true\n' + fm + "\n---\nbody\n")
                    result, model = self.run_main(self.record())
                    self.assertIsInstance(result, str)
                    self.assertIn("cannot resolve privacy", result)
                    model.assert_not_called()
                    construct.assert_not_called()
                    self.assertFalse(list(self.done.iterdir()))
            page.unlink()

    def test_bounded_quoted_privacy_and_large_body_still_block_by_session_identity(self):
        import source_links as L

        page = self.bundle / "renamed.md"
        page.write_text('---\n"no_llm": "true" # human reviewed\n'
                        'title: "A quoted title: changed"\n'
                        'sources: [{resource: "claude-session://session"}]\n'
                        'summary: |\n  Literal *aliases and << are not YAML references.\n'
                        '---\n' + "body " * L.MAX_FRONTMATTER_CHARS)
        result, model = self.run_main(self.record())
        self.assertEqual(result, 0)
        model.assert_not_called()
        self.assertTrue(D.no_llm_of_pages([], self.record()))

    def test_unreadable_or_unsupported_tail_fails_without_advancing_marker(self):
        for agent in ("claude", "codex", "unsupported"):
            rec = self.record(agent, abs_path=str(self.root / "missing.jsonl"))
            marker = self.done / (agent + "-session")
            marker.write_text(json.dumps({"last_ts": "2020-01-01T00:00:00Z", "pages": ["original"]}))
            before = marker.read_bytes()
            result, model = self.run_main(rec)
            self.assertIn("1 continuation(s) failed", str(result))
            self.assertEqual(marker.read_bytes(), before)
            model.assert_not_called()

    def test_skip_staging_failure_keeps_prior_progress(self):
        rec = self.codex_fixture()
        marker = self.done / "codex-session"
        marker.write_text(json.dumps({"last_ts": "2020-01-01T00:00:00Z", "pages": ["original"]}))
        before = marker.read_bytes()
        with patch.dict(os.environ, {"KAL_LEDGER_STAGE": str(self.root / "stage.json")}), \
                patch.object(D.ledger, "pending_keys", return_value=set()), \
                patch.object(D.ledger, "append_many", side_effect=RuntimeError("staging failed")), \
                patch.object(D.ledger, "append", side_effect=RuntimeError("staging failed")):
            with self.assertRaisesRegex(RuntimeError, "staging failed"):
                self.run_main(rec)
        self.assertEqual(marker.read_bytes(), before)


if __name__ == "__main__":
    unittest.main()
